## 공지 카테고리 분류 및 점수화

## 노트북 목적: 공지 카테고리 분류 및 점수화
이 노트북은 수집된 공지를 카테고리별로 나누고 점수화 기준을 확인하기 위한 보조·실험 노트북입니다. 장학공지, 학사공지, 채용공지 등 공지 유형별 키워드 사전을 만들고, 제목·본문·이미지 텍스트 기반 점수화 기준을 확인합니다.

카테고리 기준을 코드로 명시해두면 팀원이 분류 기준을 확인하고, 키워드 추가·수정도 비교적 쉽게 할 수 있습니다.

In [1]:
장학_공지 = {
    "국가근로장학금": [
  "국가근로장학금", "하계방학집중근로", "동계방학집중근로", "희망근로지 신청", "추가 신청", "1차 신청", "2차 신청", "3차 신청", "신규장학생 운영", "선발 발표", "사전교육", "근로 기간", "근로 장소", "교내근로", "교외근로", "공공기관", "시급", "최대 근로시간", "업무스케쥴", "출근부", "학업시간표 등록", "오리엔테이션", "부정근로", "근로자격 해제", "중복참여 불가", "장학생 준수사항", "근로지 배정", "선호학과", "근로지 담당자", "출근부 어플", "장학금 지급일", "근로지 대학제출", "학적변동", "휴학", "자퇴", "졸업", "제적", "문의", "시스템 오류", "한국장학재단 홈페이지", "모바일 어플"
],
"교내장학금": [
  "가족장학금", "수퍼스타(동문) 자녀 장학금", "다문화장학금", "장애인자녀장학금", "장애대학생장학금", "특수환경지원장학금", "장학사정관제장학금", "재단우대장학금", "신청기간", "신청자격", "성적기준", "이수학점", "평점평균", "제출서류", "가족관계증명서", "개인정보동의서", "장학금액", "지급방법", "inSTAR", "포털", "신규자", "중복수혜", "수업료 감면", "문의", "학생지원실"
],
"교외장학금": [
  "화성시인재육성재단", "하이트진로홀딩스", "강원랜드 멘토링", "전주시 글로벌 인재양성", "인천인재평생교육진흥원", "서울장학재단", "논산시장학회", "농어촌희망재단", "푸른등대 기부장학금", "부산진구장학회", "대산농촌재단", "고속도로장학재단", "은평구민장학재단", "춘천시민장학재단", "손태희장학재단", "협성문화재단", "롯데장학재단", "우아한 사장님 자녀", "미래산업인재", "지역정착 장학금", "해외연수", "해외봉사", "해외유학", "창업기숙사", "꿈드림", "멘토링", "사회리더", "기부장학", "본인부담 등록금 반값지원", "저소득 대학생", "독립유공자 후손", "북한이탈청소년", "소아청소년 당뇨인", "긴급재난 지원", "멘토단", "멘티", "활동기관", "활동계획서", "시급", "최대근로시간", "활동기간", "제출서류", "재단 홈페이지", "추천서"
],
"국가장학금": [
  "국가장학금", "이공계", "인문100년", "예술체육비전", "주거안정장학금", "신청기간", "1차", "2차", "가구원 동의", "소득분위", "지원구간", "성적기준", "신청방법", "서류제출", "지급", "선발", "학업계획서", "학업시간표", "학적변동", "구제신청", "탈락", "문의", "한국장학재단"
],
"학자금대출": [
  "학자금대출", "대출이자 지원", "신용회복 지원", "특별상환유예", "기등록자 특별승인", "농촌출신 학자금융자", "채무자 신고", "해외이주", "유학신고", "업무처리기준", "신청기간", "신청방법", "심사", "지급", "문의", "상환", "학자금지원사업", "결혼이민자", "혼인귀화자", "대학학비지원", "지방자치단체", "농어촌", "이자지원사업", "상환유예", "신용회복"
],
"멘토링/청소년교육지원": [
  "대학생 청소년교육지원사업", "멘토링", "사회리더", "멘토", "멘티", "활동계획서", "활동기관", "사전신청", "사전교육", "활동기간", "활동내용", "시급", "최대근로시간", "중복참여", "부정근로", "선발", "결과발표", "지급", "지급일", "지급방법", "온라인교육", "매뉴얼", "시스템", "어플", "홈페이지", "활동 포기", "기관-학생 상호평가", "출근부", "학업시간표 입력", "업무스케쥴", "활동기관 발굴", "신규기관 등록", "중복참여불가", "이해관계 회피", "활동시간 제한"
],
"특별지원/목회자/북한이탈/보훈": [
  "목회자 장학금", "목회자 자녀 장학금", "북한이탈주민 교육지원금", "보훈장학금", "국가보훈대상자", "국가유공자", "교육지원대상자증명서", "대학수업료등면제대상자증명서", "가족관계증명서", "재직증명서", "교회주보", "결혼이민자", "혼인귀화자", "다문화", "장애인자녀", "장애대학생", "특수환경지원", "아동복지시설", "한부모가정", "긴급재난 지원", "제출서류", "신청기간", "지급방법"
],
"글로벌/해외연수/파란사다리": [
  "글로벌 인재양성", "영어능력강화", "해외연수", "어학연수", "교환학생", "파란사다리", "Fulbright", "국제교류", "신청기간", "선발", "지원", "서류제출", "학점인정", "학적변동", "재단 홈페이지"
],
"취업연계/창업/고졸후학습자/희망사다리": [
  "중소기업 취업연계 장학금", "희망사다리", "고졸후학습자", "창업", "취업", "취업지원", "창업지원", "직무기초교육", "의무종사", "취업연계", "창업지원금", "의무재직", "일자리사업 중복참여", "사용계획서", "진단평가", "보증보험", "취업연계 상담센터", "지원사업", "심사기준", "지원금", "등록금 전액지원", "의무종사 기업기준", "재직확인"
],
"행정/안내/기타": [
  "통학로", "학생지원", "정보로", "안내", "제한대학", "지원대상", "지원방법", "제출서류", "문의", "본인부담", "등록금", "반값지원", "지역정착", "졸업", "휴학", "자퇴", "제적", "졸업예정자", "졸업유예", "학점", "평점", "성적", "학업", "학적변동", "inSTAR", "포털", "이메일", "방문접수", "팩스", "제출기한", "신청기한", "지급기한", "시스템오류", "어플오류", "홈페이지오류", "콜센터", "공지사항", "개인정보동의", "계좌등록", "지급계좌", "통장", "담당자", "연락처"
]
}
학사_공지 = {
    "수업/강의 관련": ["강의", "수업", "교과목", "강의실", "강좌", "시간표", "수강신청", "보강"],
    "시험/평가": ["시험", "수시고사", "중간고사", "기말고사", "평가", "성적", "과제", "응시"],
    "졸업/학위": ["졸업", "논문", "학위", "심사", "학점", "수료", "취업", "조기"],
    "등록/휴학/복학": ["등록", "휴학", "복학", "신청", "복학생", "편입", "자퇴"],
    "장학/재정": ["장학금", "지원", "신청서", "선발", "지급", "장학생"],
    "행사/일정": ["설명회", "일정", "행사", "참석", "기념일", "주간", "날짜", "개강", "종강", "연휴"],
    "행정/공지": ["공지", "안내", "서류", "제출", "처리", "관리", "참조", "변경"]
}
채용_공지 = {
    "조교/교육조교": ["조교", "교육조교", "학생조교", "실습조교"],
    "일반 행정직": ["행정", "사무", "일반직", "직원", "계약", "관리", "전담", "사무직", "행정직",
                  "업무", "담당", "운영", "통합"],
    "상담/지도사": ["지도사", "상담", "멘토", "컨설턴트", "진로", "코치"],
    "기술/전문직": ["개발", "소프트웨어", "빅데이터", "IT", "기술", "연구", "프로그램",
                 "데이터 분석", "연구개발", "기술지원", "산학", "협력", "정보", "프로젝트"],
    "채용 결과 안내": ["채용 결과", "합격자 발표", "결과 안내", "최종 합격", "발표", "합격"]

}
부서_분류 = {
    "학사/수업": ["학생 지원", "학생지원", "학생 역량", "학생역량", "학사지원", "학사 지원", "LINC"],
    "진로/취업":  ["대학 일자리", "대학일자리", "진로취업", "진로 취업", "학생 성공", "학생성공"],
    "장학금/지원금": [],
    "대외활동/서포터즈": [],
    "공모전/경진대회":[],
    "교내행사/이벤트": ["대학 일자리", "대학일자리", "진로취업", "진로 취업" "학생 성공", "학생성공"],
    "비교과/교육": ["대학 일자리", "대학일자리", "진로취업", "진로 취업" "학생 성공", "학생성공"],
    "군 관련": ["예비군"],
}
정리된_부서명 = [
    "LINC 3.0 사업단", "RIS 사업단", "산학연공유협업센터", "산학협력단", "산학협력지원실", "전북산학융합원",
    "학생지원실", "학생성공센터", "학생역량지원센터", "학사지원실", "장애학생지원센터", "현장실습지원센터",
    "진로개발센터", "진로취업지원실", "대학일자리+센터", "대학일자리플러스센터",
    "창업교육센터", "창업지원단",
    "교무지원실", "교수학습개발센터", "원격교육지원센터", "융합교육지원센터", "인문사회융합인재양성사업단", "수퍼스타칼리지", "융합학부",
    "국제교류원",
    "사회봉사센터", "장애학생지원센터", "전북특별자치도 청년미래센터", "인권센터",
    "빅데이터센터", "정보통신지원실", "과학기술정보통신부 중앙전파관리소",
    "총무지원실", "재무지원실", "시설지원실", "통합관리자", "중앙선거관리위원회", "관리자",
    "RC센터", "로컬벤처학부", "카운슬링센터"
]
#test
'''
"동아리/모임": ["동아리", "소모임", "학회", "스터디", "자치기", "모임", "커뮤니티", "멘토링", "응원단", "자치", "모임",
                 "동아리", "소모임", "멘티", "멘토"],
"행정/일반공지": ["안내", "공지", "등록", "변경", "알림", "신청", "연장", "마감", "수정", "협력", "접수", "설문조사",
                   "공고", "발표", "전형", "제출", "예고", "공지사항", "확인", "마감", "공지", "행정", "수정"],
 "기타/특수": ["국제", "글로벌", "해외", "유학", "교환학생", "단기", "파견", "창업", "창조경제", "기술", "플랫폼",
                "네트워크", "데이터", "혁신", "리더십", "비즈니스", "문화", "디자인", "봉사활동", "문제해결", "직업",
                "관광", "인공지능", "코칭", "학습", "분석", "기타", "다문화", "글로벌"]'''

'\n"동아리/모임": ["동아리", "소모임", "학회", "스터디", "자치기", "모임", "커뮤니티", "멘토링", "응원단", "자치", "모임",\n                 "동아리", "소모임", "멘티", "멘토"],\n"행정/일반공지": ["안내", "공지", "등록", "변경", "알림", "신청", "연장", "마감", "수정", "협력", "접수", "설문조사",\n                   "공고", "발표", "전형", "제출", "예고", "공지사항", "확인", "마감", "공지", "행정", "수정"],\n "기타/특수": ["국제", "글로벌", "해외", "유학", "교환학생", "단기", "파견", "창업", "창조경제", "기술", "플랫폼",\n                "네트워크", "데이터", "혁신", "리더십", "비즈니스", "문화", "디자인", "봉사활동", "문제해결", "직업",\n                "관광", "인공지능", "코칭", "학습", "분석", "기타", "다문화", "글로벌"]'

### 일반공지 분류 키워드 사전
일반공지에 자주 등장하는 수업, 졸업, 행사, 행정, 국제교류 등 주제별 키워드를 정의합니다. 제목과 본문에 포함된 단어를 이 사전과 비교해 공지의 성격을 추정합니다.

In [2]:
#공지별 카테고리 키워드
일반_공지 = {
    "학사/수업": [
        "수강", "학기", "학점", "교육과정", "졸업", "교과목", "학사", "성적", "교양", "졸업생", "방학",
        "편입", "전공", "교환학생", "학업", "학위", "학력", "복학", "기숙사 입주",
        "학부", "학과", "수업", "실습", "학사", "수강신청", "교육"],
    "진로/취업": [
        "취업", "진로", "채용", "입사", "직무", "일자리", "인턴", "커리어", "직업", "잡콘서트",
        "일자리", "일자리박람회", "커리어"],
    "장학금/지원금": [
        "장학금", "장학", "장학생", "지원금", "학자금지원", "학자금 지원", "근로장학",  "근로 장학", "성적 장학", "성적장학", "등록금 감면", "장학 재단",
        "장학재단", "학비 지원", "학비지원"],
    "대외활동/서포터즈": [
        "서포터즈", "기자단", "홍보대사", "대외활동", "봉사단", "체험단", "멘토단", "자원봉사",
        "자원봉사자", "활동", "캠프", "행사", "봉사활동", "봉사자", "대사", "봉사", "응원단", "자원봉사", "자치기구"],
    "공모전/경진대회": [
        "공모전", "대회", "경진대회", "콘테스트", "아이디어", "캠프", "경진 대회", "해커톤"],
    "교내행사/이벤트": [
        "행사", "축제", "페스티벌", "박람회", "설명회", "콘서트", "캠프", "포럼", "세미나", "이벤트",
        "연합", "학회", "학술제", "학술대회", "워크숍", "온스타", "onSTAR", "초청", "참가자", "기념",
        "설명", "진행", "공연", "심포지엄", "전시", "라이브", "공모전", "경진대회", "문화제", "공연", "음악회",
        "단체 활동", "대동제", "대회", "페어", "파티", "축하", "컨퍼런스"],
    "비교과/교육": [
        "프로그램", "프로그램 안내", "프로그램안내", "지원 프로그램", "특강", "비교과", "워크숍", "세미나", "교육", "학습법",
        "연수", "강좌", "동아리", "소모임", "영어", "스터디", "멘토링", "온스타", "onSTAR", "예치금","역량",
        "과정", "실습", "학습", "역량 강화", "교육과정", "강의", "자격증", "취득", "학습자", "훈련", "강좌", "SP", "CP",
        "자격", "성장", "훈련", "학습법", "기초", "심화", "학점", "교양", "전공", "학습법", "성적", "공부", "실습", "과제"],
    "군 관련": [
        "예비군", "병역", "군입대", "훈련", "복무", "군대", "입대", "전역", "병사", "장교", "부사관", "훈련소",
        "군사", "복무기간", "병역의무", "군생활", "군 입대", "국방", "훈련소", "기초군사훈련", "동원훈련",
        "병역법", "군인", "군복무", "병역제도", "국방부", "예비군 훈련"],
    "창업 관련": [
          "창업", "창업 캠프"],
    "행정" : ["행정", "결과 안내"],
    "기타" : ["%%%%%%%"]
}

## 테스트용 키워드 사전

### 테스트용 일반공지 키워드 사전
분류 품질을 개선하기 위해 키워드 범위를 확장하거나 조정한 테스트용 사전입니다. 실제 적용 전, 유사어·띄어쓰기·행정 표현 차이를 반영해 분류 누락을 줄이려는 검토 과정입니다.

In [3]:
일반_공지t = {
    "학사/수업": [
    # 일반 학사 관련
    "수강", "수강신청", "교육과정", "교육 과정", "수강편람", "교과목", "수업 계획서", "강의 계획서",
    "졸업 요건", "졸업요건", "졸업논문", "졸업 자격", "졸업심사", "졸업 학점", "졸업생", "졸업증명서",
    "학위", "학위수여", "학위취득", "학사", "학사 일정", "학사 공지", "학사 안내", "수강 편람",
    "교양", "교양과목", "교양 필수", "교양 선택", "교양 수업", "기초과목", "기초학문",
    # 전공 및 편입
    "전공", "전공과목", "전공필수", "전공 선택", "전공 학점", "전공 심화", "전공 트랙", "편입", "편입생", "전과",
    "복수전공", "부전공", "심화전공", "전공교과", "전공필수", "전공학점",
    # 학적 관련
    "학적", "학적변동", "복학", "휴학", "재입학", "재학", "전과", "전입", "복수전공", "부전공", "학적변동",
    "재학생", "편입생", "복학생", "입학", "신입생", "편입생", "기숙사 입주", "기숙사 신청",
    # 교환학생 및 국제 학사
    "교환학생", "해외연수", "국제교류", "어학연수", "해외 대학", "교환 프로그램", "글로벌 프로그램", "유학생",
    "국제 학생", "국제 교류", "유학", "국제학기", "해외 수업", "국제 수강", "해외 학기",
    # 성적 및 평가
    "성적", "성적표", "성적 확인", "성적 평가", "평점", "GPA", "평균학점", "성적 관리", "성적 처리", "성적 우수",
    "성적 경고", "성적 인증", "성적 증명서", "성적포기", "학점 포기", "성적 이수",
    # 실습 및 현장 학습
    "실습", "현장실습", "현장학습", "인턴십", "실습 과목", "실습 보고서", "실습 평가", "산학협력", "실습 학점",
    "산업체 연계", "실습 지원", "현장 학점", "현장 평가",
    # 기타 학사 관련
    "교육 편람", "교육 과정", "수업", "강의",
    "강의실", "강의평가", "강의 계획서", "학습 자료", "수강료", "과제 제출", "출석", "출석 인정", "출결",
    "기초 교육", "심화 교육", "기초 수업", "심화 수업", "수업 평가", "출석률"
],
    "진로/취업": [
        "취업", "진로", "채용", "입사", "직무", "일자리", "인턴", "커리어", "직업", "잡콘서트",
        "일자리", "일자리박람회", "커리어"],
    "장학금/지원금": [
        "장학금", "장학", "장학생", "지원금", "학자금지원", "학자금 지원", "근로장학",  "근로 장학", "성적 장학", "성적장학", "등록금 감면", "장학 재단",
        "장학재단", "학비 지원", "학비지원"],
    "대외활동/서포터즈": [
        "서포터즈", "기자단", "홍보대사", "대외활동", "봉사단", "체험단", "멘토단", "자원봉사",
        "자원봉사자", "활동", "캠프", "행사", "봉사활동", "봉사자", "대사", "봉사", "응원단", "자원봉사", "자치기구"],
    "공모전/경진대회": [
        "공모전", "대회", "경진대회", "콘테스트", "아이디어", "캠프", "경진 대회", "해커톤"],
    "교내행사/이벤트": [
        "행사", "축제", "페스티벌", "박람회", "설명회", "콘서트", "캠프", "포럼", "세미나", "이벤트",
        "연합", "학회", "학술제", "학술대회", "워크숍", "온스타", "onSTAR", "초청", "참가자", "기념",
        "설명", "진행", "공연", "심포지엄", "전시", "라이브", "공모전", "경진대회", "문화제", "공연", "음악회",
        "단체 활동", "대동제", "대회", "페어", "파티", "축하", "컨퍼런스"],
    "비교과/교육": [
        "프로그램", "프로그램 안내", "프로그램안내", "지원 프로그램", "특강", "비교과", "워크숍", "세미나", "교육", "학습법",
        "연수", "강좌", "동아리", "소모임", "영어", "스터디", "멘토링", "온스타", "onSTAR", "예치금","역량",
        "과정", "실습", "학습", "역량 강화", "교육과정", "강의", "자격증", "취득", "학습자", "훈련", "강좌", "SP", "CP",
        "자격", "성장", "훈련", "학습법", "기초", "심화", "학점", "교양", "전공", "학습법", "성적", "공부", "실습", "과제"],
    "군 관련": [
        "예비군", "병역", "군입대", "훈련", "복무", "군대", "입대", "전역", "병사", "장교", "부사관", "훈련소",
        "군사", "복무기간", "병역의무", "군생활", "군입대", "국방", "예비", "훈련소", "기초군사훈련", "동원훈련",
        "복무 제도", "병역법", "군인", "군복무", "군입대", "병역제도", "국방부", "예비군 훈련", "훈련소"],
    "창업 관련": [
          "창업", "창업 캠프", "품평회" ],
    "행정" : ["행정", "결과 안내"],
    "기타" : ["%%%%%%%"]
}

## 카테고리 점수화 로직

## 카테고리 점수화 함수
이 셀은 제목, 본문, 부서, 이미지 OCR 텍스트에 포함된 키워드를 세고, 필드별 가중치를 적용해 카테고리 점수를 계산합니다.

현재 가중치 구조는 다음 의도를 갖습니다.
- 제목: 공지의 핵심 주제가 직접 드러나므로 높은 가중치
- 본문: 세부 맥락을 보완하는 가중치
- 부서: 담당 부서를 통해 주제를 추정하는 보조 가중치
- 이미지 텍스트: 포스터형 공지에서 누락 정보를 보완하는 가중치

이 점수는 LLM 응답 이전 단계에서 질문과 관련 있는 공지를 먼저 좁히는 규칙 기반 전처리 값으로 사용합니다.

In [5]:
import pandas as pd
File_title = "일반공지"
# 🔹 CSV 파일 로드
file_path = "일반공지+이미지텍스트_포함.csv"
df = pd.read_csv(file_path)

# 🔹 키워드 정의 (간략 버전)
category_dict = {
    "일반공지": 일반_공지,
    "장학공지": 장학_공지,
    "학사공지": 채용_공지
}
department_dict = {
    "일반공지": 부서_분류,
    "장학공지": 부서_분류,
    "학사공지": 부서_분류
}
# 가중치 설정
TITLE_WEIGHT = 3
CONTENT_WEIGHT = 2
DEPT_WEIGHT = 0
IMAGE_WEIGHT = 2

def calculate_category_scores_by_notice_type(df: pd.DataFrame) -> pd.DataFrame:

    def calculate_score(title, content, dept, image, category_keywords, department_keywords):
        title = str(title) if pd.notna(title) else ""
        content = str(content) if pd.notna(content) else ""
        dept = str(dept) if pd.notna(dept) else ""
        image = str(image) if pd.notna(image) else ""

        scores = {k: 0 for k in category_keywords.keys()}

        for cat, keywords in category_keywords.items():
            scores[cat] += (sum(title.count(k) for k in keywords) * TITLE_WEIGHT * 10) / (len(title) + 1)
            scores[cat] += (sum(content.count(k) for k in keywords) * CONTENT_WEIGHT * 10) / (len(content) + 1)
            scores[cat] += (sum(image.count(k) for k in keywords) * IMAGE_WEIGHT * 10) / (len(image) + 1)

        for cat, keywords in department_keywords.items():
            if cat in scores:
                scores[cat] += (sum(dept.count(k) for k in keywords) * DEPT_WEIGHT * 10) / (len(dept) + 1)

        if all(v == 0 for v in scores.values()):
            scores["기타"] = 1.0

        return scores

    # 점수 계산 및 열 추가
    result_df = df.copy()
    for idx, row in result_df.iterrows():
        noti_type = row.get("공지분류", "").strip()
        category_keywords = category_dict.get(noti_type, {})
        department_keywords = department_dict.get(noti_type, {})

        title = row.get("공지 제목", "")
        content = row.get("본문 내용", "")
        dept = row.get("부서", "")
        image = row.get("이미지 텍스트", "")

        scores = calculate_score(title, content, dept, image, category_keywords, department_keywords)

        for cat, score in scores.items():
            colname = f"{noti_type}_{cat}"
            if colname not in result_df.columns:
                result_df[colname] = 0.0
            result_df.at[idx, colname] = score

    return result_df


#step6. 카테고리분류 지정
print("---> step6 시작")
try:
    step6_df = calculate_category_scores_by_notice_type(df)

    #파일 저장
    file_name = f"①_{File_title}+카테고리분류({TITLE_WEIGHT}-{CONTENT_WEIGHT}-{DEPT_WEIGHT}-{IMAGE_WEIGHT}).csv"
    step6_df.to_csv(file_name, index=False, encoding='utf-8-sig')
    print(f"---> step6 완료 : 저장파일명 = {file_name}")
except Exception as e:
    print("---> step6 실패")
    print(f"에러 내용: {e}")


# 🔹 최종 데이터프레임 출력
step6_df

---> step6 시작
---> step6 완료 : 저장파일명 = ①_일반공지+카테고리분류(3-2-0-2).csv

,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,이미지 링크,이미지 텍스트,_기타
0,공지,공지+관리자_ 백마응원단에서 신입단원을 모집합니다,전주대학교 백마응원단에서 신입단원을 모집합니다,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,"안녕하세요, 전주대학교 학생 여러분전주대학교의 새로운 응원 문화를 선도할 백마응원...",NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,전주대학교 백마용원단 모집 2025년 열정 가득한 당신올 기다립니다] TM 3 JU...,1.0
1,공지,공지+관리자_제13회 미래전북포럼 개최 안내,제13회 미래전북포럼 개최 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,"제13회 미래전복포럼 ""국가슴단전락산업과 전북특별자치도의 성장동력' 2025. 4....",1.0
2,공지,공지+관리자_장(학생)예비군 전입신고서 제출 안내,2025학년도 1학기 직장(학생)예비군 전입신고서 제출 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,* 자세한 내용은 첨부문서 참조,NaN,NaN,NaN,1.0
3,7492,7492+RIS사업단_차 수준별 기초학력증진 프로그램 안내,2025학년도 JST 공유대학 제1차 수준별 기초학력증진 프로그램 안내,RIS사업단,2025-04-02,138,https://www.jj.ac.kr/jj/community/notice01.do?...,신청기간: 2025. 4. 1.(화) ~ 2025. 4. 10.(목)신청방법: JS...,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,2D25학년도 구준별 기고학력증진 프로그램 신청대상 전북피역학민플렉품 팔여대학 학부...,1.0
4,7491,7491+대학일자리플러스센터_Dream-JOB 스터디 참여자 모집,[대학일자리플러스센터] 2025학년도 Dream-JOB 스터디 참여자 모집,대학일자리플러스센터,2025-04-01,155,https://www.jj.ac.kr/jj/community/notice01.do?...,취업을 준비 중이신가요?같은 기업 혹은 직무를 목표로 하는 팀들과 함께하는실전 취업...,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,슈퍼스다클 키우는 전주대학교 대학일자리플러스센터 여러분의 드림잡 J 이제 함께 이루...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,7000,7000+융합교육지원센터_총 장학금 400만원/~11월 5일),2023학년도 자기설계전공 교육과정 공모전(총 장학금 400만원/~11월 5일),융합교육지원센터,2023-10-04,772,https://www.jj.ac.kr/jj/community/notice01.do?...,1. 공모전 개요가. 공모 명: 자기설계연계전공 교육과정 공모전 등나. 사업기간: ...,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,전주대학교 ! 교육학신본부 전공과 교라목울 내뜻으로 설계해보자! 자기설계전공 교육과...,1.0
496,6999,6999+교수학습개발센터_학생주도)실전에서 사용하는 발표 꿀팁,[교수학습개발센터] JJ 학습법 특강 - (학생주도)실전에서 사용하는 발표 꿀팁,교수학습개발센터,2023-10-04,387,https://www.jj.ac.kr/jj/community/notice01.do?...,"2023-1학기 학습법노하우 경진대회 수상자, 한식조리학과 김근아 학생에게서 듣는 ...",NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,터표이 J용O관 말표3 올텔 66 한식조리학과 김근아 학생이 알려주는 발표 꿀립! ...,1.0
497,6998,6998+통합 관리자_개인정보 분쟁조정제도 강화 안내,개인정보 분쟁조정제도 강화 안내,통합 관리자,2023-10-04,417,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,국민의 권리구제 강화 개인정보보호 위원 회 개인정보분쟁조정위원회 개인정보 분쟁조정이...,1.0
498,6997,6997+교무지원실_단체교섭 요구 노동조합 확정공고,단체교섭 요구 노동조합 확정공고,교무지원실,2023-09-28,522,https://www.jj.ac.kr/jj/community/notice01.do?...,단체교섭 요구 노동조합 확정공고「교원의 노동조합 설립 및 운영 등에 관한 법률」제6...,NaN,NaN,NaN,1.0
499,6996,"6996+장애학생지원센터_형 인턴(일반, 장애인) 채용 안내","2023년 하반기 KOTRA 체험형 인턴(일반, 장애인) 채용 안내",장애학생지원센터,2023-09-27,535,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,ROIRA 대7점 인터 (장애인 전험) 모집공고 2023-2호 2023년 체험형...,1.0

### 분류 함수 실행 결과 확인
정의한 점수화 함수를 실제 데이터프레임에 적용하고 결과를 확인하는 셀입니다. 상위 카테고리와 점수 분포를 눈으로 보며 키워드 사전이나 가중치를 조정할 수 있습니다.

In [8]:
step6_df = calculate_category_scores_by_notice_type(df)
step6_df

,공지분류,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,...,장학공지_국가근로장학금,장학공지_교내장학금,장학공지_교외장학금,장학공지_국가장학금,장학공지_학자금대출,장학공지_멘토링/청소년교육지원,장학공지_특별지원/목회자/북한이탈/보훈,장학공지_글로벌/해외연수/파란사다리,장학공지_취업연계/창업/고졸후학습자/희망사다리,장학공지_행정/안내/기타
0,일반공지,공지,공지+관리자_5년 하우와우미래캠프 2기 멘티 모집,[산학협력단] 2025년 하우와우미래캠프 2기 멘티 모집,관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice01.do?...,전북특별자치도의 특화분야 멘토-멘티 매칭을 통해 지역미래(청년)세대 육성을 위한'하...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,일반공지,공지,공지+관리자_2025학년도 천잠 대동제 안내,2025학년도 천잠 대동제 안내,관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice01.do?...,<행사 개요>1. 행사명: 2025학년도 천잠 대동제_ Triplog: 청춘의 기록...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,일반공지,공지,공지+관리자_ 직장(학생) 예비군 소집훈련 안내문,2025년도 대학 직장(학생) 예비군 소집훈련 안내문,관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice01.do?...,2025년도 대학 직장(학생)예비군 소집훈련 안내문 입니다.2025년도 1학기에 본...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,일반공지,7539,7539+대학일자리플러스센터_역량강화교육 컴퓨터자격증반 운영 안내,2025학년도 하계방학 디지털역량강화교육 컴퓨터자격증반 운영 안내,대학일자리플러스센터,2025-05-26,39,https://www.jj.ac.kr/jj/community/notice01.do?...,2025학년도하계방학 디지털역량강화교육 컴퓨터자격증반 안내비고●모집기간각 프로그램 ...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,장학공지,공지,공지+관리자_. 23. 9시~6. 23. 18시),2025-2학기 국가근로장학금 1차 신청 안내(5. 23. 9시~6. 23. 18시),관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,<2025학년도2학기 국가근로장학금1차 신청 안내>2025학년도2학기 국가근로장학금...,NaN,...,1.599810,0.076046,0.015209,0.913973,0.076046,0.106464,0.045627,0.197719,0.060837,0.837928
5,장학공지,공지,"공지+관리자_기간(1차, 5/23~6/23) 안내","2025-2학기 국가장학금 신청기간(1차, 5/23~6/23) 안내",관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,"2025-2학기 국가장학금 1차 신청 기간을 안내하오니,모든 학생들은 신청 바랍니다...",NaN,...,0.235294,0.789474,0.000000,2.839009,0.789474,0.000000,0.789474,0.789474,0.000000,1.024768
6,장학공지,공지,공지+관리자_ 안내: 5/23(금)~6/23(월),25-2학기 주거안정장학금 신청 일정 안내: 5/23(금)~6/23(월),관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,"가. 부모 모두의 주민등록상 주소지가 원거리(전주시, 익산시, 김제시를 제외한 지역...",NaN,...,0.000000,0.123457,0.000000,0.916893,0.123457,0.123457,0.000000,0.000000,0.000000,1.040349
7,장학공지,공지,공지+관리자_ 20. 10시~5. 29. 18시),2025학년도 국가근로장학금 하계방학 집중근로 희망근로지 신청 안내(5. 20. 1...,관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,2025학년도 국가근로장학금 하계방학 집중근로 희망근로지 신청 안내(5. 20. 1...,NaN,...,1.298666,0.037807,0.037807,0.264650,0.063012,0.226843,0.000000,0.214241,0.025205,0.643032
8,장학공지,공지,공지+관리자_정관제장학금 신청안내(~6. 13.),2025-1학기 장학사정관제장학금 신청안내(~6. 13.),관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,1. 신청 대상장학사정관제장학금은 아래 유형 중 하나에 해당하는 본교 재학생에게 지...,NaN,...,0.129032,1.167155,0.018433,0.258065,0.239631,0.165899,0.055300,0.036866,0.000000,1.259321
9,장학공지,공지,공지+관리자_녀 장학금 신청 안내(~5. 30.),2025학년도 수퍼스타(동문) 자녀 장학금 신청 안내(~5. 30.),관리자,2025-05-26,0,https://www.jj.ac.kr/jj/community/notice03.do?...,2025학년도 수퍼스타(동문) 자녀 장학금을 지급하고자 하오니 해당 학생은 아래 내...,NaN,...,0.128755,1.284252,0.042918,0.429185,0.386266,0.257511,0.171674,0.171674,0.000000,1.112578

## 일반공지 분류 실험

## 일반공지 분류 실험
마감일 추출까지 끝난 일반공지·장학공지 944건의 통합공지 데이터를 대상으로 카테고리 점수를 계산하는 실험 셀입니다. 공지 유형별로 키워드 사전을 다르게 적용하기 위해 `noti_case`를 두고, 제목·본문·부서·이미지 텍스트 가중치를 조정합니다.

In [ ]:
import pandas as pd

# 🔹 파일 로드 (사용할  CSV파일 이름 입력)
file_path = "통합공지_(마감일추출포함).csv"
df = pd.read_csv(file_path)
noti_case = '일반'

# 🔹 카테고리 그룹 딕셔너리
if noti_case == '일반':
    category_keywords = 일반_공지
    department_keywords = 부서_분류
elif noti_case == '장학':
    category_keywords = 장학_공지
    department_keywords = 부서_분류
elif noti_case == '채용':
    category_keywords = 채용_공지
    department_keywords = 부서_분류
elif noti_case == '학사':
    category_keywords = 학사_공지
    department_keywords = 부서_분류

# 🔹 가중치 설정
TITLE_WEIGHT = 3     # 공지 제목
CONTENT_WEIGHT = 2   # 본문 내용
DEPT_WEIGHT = 0      # 부서 이름
IMAGE_WEIGHT = 2     # 이미지 텍스트

# 🔹 카테고리 점수 환산 함수 (문자열 길이 기반)
def calculate_category_scores(title, content, dept, image_text):
    # NaN 처리
    title = str(title) if pd.notna(title) else ""
    content = str(content) if pd.notna(content) else ""
    dept = str(dept) if pd.notna(dept) else ""
    image_text = str(image_text) if pd.notna(image_text) else ""

    # 카테고리별 점수 초기화
    category_scores = {category: 0 for category in category_keywords.keys()}

    # 🔸 공지 제목 점수
    for category, keywords in category_keywords.items():
        title_count = sum(title.count(keyword) for keyword in keywords)
        category_scores[category] += ( title_count * TITLE_WEIGHT*10 ) / (len(title) + 1)

    # 🔸 본문 내용 점수
    for category, keywords in category_keywords.items():
        content_count = sum(content.count(keyword) for keyword in keywords)
        category_scores[category] += ( content_count * CONTENT_WEIGHT*10 ) / (len(content) + 1)

    # 🔸 부서 이름 점수
    for category, keywords in department_keywords.items():
        dept_count = sum(dept.count(keyword) for keyword in keywords)
        if category in category_scores:
            category_scores[category] += ( dept_count * DEPT_WEIGHT*10 ) / (len(dept) + 1)

    # 🔸 이미지 텍스트 점수
    for category, keywords in category_keywords.items():
        image_count = sum(image_text.count(keyword) for keyword in keywords)
        category_scores[category] += ( image_count * IMAGE_WEIGHT*10 ) / (len(image_text) + 1)

    # 🔹 모든 점수가 0일 경우 "기타" 카테고리 추가
    if all(score == 0 for score in category_scores.values()):
        category_scores["기타"] = 1.0

    return category_scores

# 🔹 데이터프레임에 카테고리 점수 추가
category_columns = list(category_keywords.keys()) + ["기타"]
for col in category_columns:
    if col not in df.columns:
        df[col] = 0.0

# 🔹 각 공지사항에 대해 점수 계산
for idx, row in df.iterrows():
    title = row.get("공지 제목", "")
    content = row.get("본문 내용", "")
    dept = row.get("부서", "")
    image_text = row.get("이미지 텍스트", "")

    scores = calculate_category_scores(title, content, dept, image_text)
    for category, score in scores.items():
        df.at[idx, category] = score

# 🔹 결과 저장
output_file = f"①_{noti_case}+마감일v1_카테고리_점수환산({TITLE_WEIGHT}-{CONTENT_WEIGHT}-{DEPT_WEIGHT}-{IMAGE_WEIGHT}).csv"
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: {output_file}")

# 🔹 최종 데이터프레임 출력
df

✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: ①_일반+마감일v1_카테고리_점수환산(3-2-0-2).csv

,Unnamed: 0,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,...,진로/취업,장학금/지원금,대외활동/서포터즈,공모전/경진대회,교내행사/이벤트,비교과/교육,군 관련,창업 관련,행정,기타
0,0,공지,공지+관리자_ 백마응원단에서 신입단원을 모집합니다,전주대학교 백마응원단에서 신입단원을 모집합니다,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,"안녕하세요, 전주대학교 학생 여러분전주대학교의 새로운 응원 문화를 선도할 백마응원...",NaN,...,0.000000,0.189573,1.438746,0.000000,0.113960,0.094787,0.000000,0.0,0.000000,0.0
1,1,공지,공지+관리자_제13회 미래전북포럼 개최 안내,제13회 미래전북포럼 개최 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,1.731884,0.130435,0.000000,0.0,0.021739,0.0
2,2,공지,공지+관리자_장(학생)예비군 전입신고서 제출 안내,2025학년도 1학기 직장(학생)예비군 전입신고서 제출 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,* 자세한 내용은 첨부문서 참조,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.882353,0.0,0.000000,0.0
3,3,7492,7492+RIS사업단_차 수준별 기초학력증진 프로그램 안내,2025학년도 JST 공유대학 제1차 수준별 기초학력증진 프로그램 안내,RIS사업단,2025-04-02,138,https://www.jj.ac.kr/jj/community/notice01.do?...,신청기간: 2025. 4. 1.(화) ~ 2025. 4. 10.(목)신청방법: JS...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.502366,0.000000,0.0,0.000000,0.0
4,4,7491,7491+대학일자리플러스센터_Dream-JOB 스터디 참여자 모집,[대학일자리플러스센터] 2025학년도 Dream-JOB 스터디 참여자 모집,대학일자리플러스센터,2025-04-01,155,https://www.jj.ac.kr/jj/community/notice01.do?...,취업을 준비 중이신가요?같은 기업 혹은 직무를 목표로 하는 팀들과 함께하는실전 취업...,NaN,...,2.387907,0.000000,0.092379,0.000000,0.092379,1.207284,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,7000,7000+융합교육지원센터_총 장학금 400만원/~11월 5일),2023학년도 자기설계전공 교육과정 공모전(총 장학금 400만원/~11월 5일),융합교육지원센터,2023-10-04,772,https://www.jj.ac.kr/jj/community/notice01.do?...,1. 공모전 개요가. 공모 명: 자기설계연계전공 교육과정 공모전 등나. 사업기간: ...,NaN,...,0.041572,1.665912,0.000000,0.870086,0.870086,5.032939,0.000000,0.0,0.000000,0.0
496,496,6999,6999+교수학습개발센터_학생주도)실전에서 사용하는 발표 꿀팁,[교수학습개발센터] JJ 학습법 특강 - (학생주도)실전에서 사용하는 발표 꿀팁,교수학습개발센터,2023-10-04,387,https://www.jj.ac.kr/jj/community/notice01.do?...,"2023-1학기 학습법노하우 경진대회 수상자, 한식조리학과 김근아 학생에게서 듣는 ...",NaN,...,0.000000,0.000000,0.000000,0.130719,0.332133,5.393891,0.000000,0.0,0.000000,0.0
497,497,6998,6998+통합 관리자_개인정보 분쟁조정제도 강화 안내,개인정보 분쟁조정제도 강화 안내,통합 관리자,2023-10-04,417,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0
498,498,6997,6997+교무지원실_단체교섭 요구 노동조합 확정공고,단체교섭 요구 노동조합 확정공고,교무지원실,2023-09-28,522,https://www.jj.ac.kr/jj/community/notice01.do?...,단체교섭 요구 노동조합 확정공고「교원의 노동조합 설립 및 운영 등에 관한 법률」제6...,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0
499,499,6996,"6996+장애학생지원센터_형 인턴(일반, 장애인) 채용 안내","2023년 하반기 KOTRA 체험형 인턴(일반, 장애인) 채용 안내",장애학생지원센터,2023-09-27,535,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,1.770634,0.000000,0.016584,0.000000,0.033167,0.066335,0.000000,0.0,0.000000,0.0

## 분류 검증 코드

### 분류 검증용 상세 결과 생성
카테고리 점수뿐 아니라 어떤 키워드가 어느 필드에서 매칭됐는지 확인하기 위한 검증용 출력입니다. 분류 결과가 이상할 때 원인을 추적하고 키워드 사전을 수정하는 데 사용됩니다.

In [ ]:
import pandas as pd

# 🔹 파일 로드 (사용할  CSV파일 이름 입력)
file_path = "일반공지+이미지텍스트_포함.csv"
df = pd.read_csv(file_path)
noti_case = '일반'

# 🔹 키워드 사전 정의
# 아래는 예시이며 실제 실행 시에는 해당 변수들이 정의되어 있어야 합니다.
# from 외부_모듈_또는_사전_정의 import 일반_공지, 장학_공지, 채용_공지, 학사_공지, 부서_분류

if noti_case == '일반':
    category_keywords = 일반_공지
    department_keywords = 부서_분류
elif noti_case == '장학':
    category_keywords = 장학_공지
    department_keywords = 부서_분류
elif noti_case == '채용':
    category_keywords = 채용_공지
    department_keywords = 부서_분류
elif noti_case == '학사':
    category_keywords = 학사_공지
    department_keywords = 부서_분류

# 🔹 가중치 설정
TITLE_WEIGHT = 3
CONTENT_WEIGHT = 2
DEPT_WEIGHT = 0
IMAGE_WEIGHT = 2

# 🔹 점수 계산 함수
def calculate_category_scores(title, content, dept, image_text):
    title = str(title) if pd.notna(title) else ""
    content = str(content) if pd.notna(content) else ""
    dept = str(dept) if pd.notna(dept) else ""
    image_text = str(image_text) if pd.notna(image_text) else ""

    total_length = len(title) + len(content) + 1  # 0 방지
    category_scores = {cat: 0 for cat in category_keywords}
    category_weights = {}

    for cat, keywords in category_keywords.items():
        t_score = (sum(title.count(k) for k in keywords) * TITLE_WEIGHT  *10 ) / (len(title) + 1)
        c_score = (sum(content.count(k) for k in keywords) * CONTENT_WEIGHT * 10 ) / (len(content) + 1)
        i_score = (sum(image_text.count(k) for k in keywords) * IMAGE_WEIGHT *10 ) / (len(image_text) + 1)


        category_scores[cat] += t_score + c_score + i_score
        category_weights[cat] = f"제목{t_score}/본문{c_score}/이미지{i_score}"

    for cat, keywords in department_keywords.items():
        d_score = sum(dept.count(k) for k in keywords) * DEPT_WEIGHT
        if cat in category_scores:
            category_scores[cat] += d_score
            category_weights[cat] += f"/부서{d_score}"

    final_scores = {}
    final_weights = {}
    if all(score == 0 for score in category_scores.values()):
        final_scores["기타"] = 1.0
    else:
        for cat, score in category_scores.items():
            if score > 0:
                final_weights[cat] = category_weights[cat]

    return final_scores, final_weights

# 🔹 결과 열 초기화
category_columns = list(category_keywords.keys()) + ["기타"]
for cat in category_columns:
    df[cat] = 0.0
    df[f"{cat}_가중치"] = ""

# 🔹 점수 계산 적용
for idx, row in df.iterrows():
    title = row.get("공지 제목", "")
    content = row.get("본문 내용", "")
    dept = row.get("부서", "")
    image_text = row.get("이미지 텍스트", "")

    scores, weights = calculate_category_scores(title, content, dept, image_text)
    for cat, score in scores.items():
        df.at[idx, cat] = score
    for cat, detail in weights.items():
        df.at[idx, f"{cat}_가중치"] = detail

# 🔹 결과 저장
output_file = f"①_가중치_{noti_case}_카테고리_점수환산({TITLE_WEIGHT}-{CONTENT_WEIGHT}-{DEPT_WEIGHT}-{IMAGE_WEIGHT})_with_detail.csv"
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"✅ 카테고리 점수가 포함된 파일이 저장되었습니다: {output_file}")

# 🔹 결과 출력
df

✅ 카테고리 점수가 포함된 파일이 저장되었습니다: ①_가중치_일반_카테고리_점수환산(3-2-0-2)_with_detail.csv

,Unnamed: 0,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,...,비교과/교육,비교과/교육_가중치,군 관련,군 관련_가중치,창업 관련,창업 관련_가중치,행정,행정_가중치,기타,기타_가중치
0,0,공지,공지+관리자_ 백마응원단에서 신입단원을 모집합니다,전주대학교 백마응원단에서 신입단원을 모집합니다,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,"안녕하세요, 전주대학교 학생 여러분전주대학교의 새로운 응원 문화를 선도할 백마응원...",NaN,...,0.0,제목0.0/본문0.0/이미지0.0947867298578199/부서0,0.0,,0.0,,0.0,,0.0,
1,1,공지,공지+관리자_제13회 미래전북포럼 개최 안내,제13회 미래전북포럼 개최 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.0,제목0.0/본문0.0/이미지0.13043478260869565/부서0,0.0,,0.0,,0.0,제목0.0/본문0.0/이미지0.021739130434782608,0.0,
2,2,공지,공지+관리자_장(학생)예비군 전입신고서 제출 안내,2025학년도 1학기 직장(학생)예비군 전입신고서 제출 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,* 자세한 내용은 첨부문서 참조,NaN,...,0.0,,0.0,제목0.8823529411764706/본문0.0/이미지0.0/부서0,0.0,,0.0,,0.0,
3,3,7492,7492+RIS사업단_차 수준별 기초학력증진 프로그램 안내,2025학년도 JST 공유대학 제1차 수준별 기초학력증진 프로그램 안내,RIS사업단,2025-04-02,138,https://www.jj.ac.kr/jj/community/notice01.do?...,신청기간: 2025. 4. 1.(화) ~ 2025. 4. 10.(목)신청방법: JS...,NaN,...,0.0,제목2.25/본문0.0/이미지0.25236593059936907/부서0,0.0,,0.0,,0.0,,0.0,
4,4,7491,7491+대학일자리플러스센터_Dream-JOB 스터디 참여자 모집,[대학일자리플러스센터] 2025학년도 Dream-JOB 스터디 참여자 모집,대학일자리플러스센터,2025-04-01,155,https://www.jj.ac.kr/jj/community/notice01.do?...,취업을 준비 중이신가요?같은 기업 혹은 직무를 목표로 하는 팀들과 함께하는실전 취업...,NaN,...,0.0,제목0.7142857142857143/본문0.35443037974683544/이미지...,0.0,,0.0,,0.0,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,7000,7000+융합교육지원센터_총 장학금 400만원/~11월 5일),2023학년도 자기설계전공 교육과정 공모전(총 장학금 400만원/~11월 5일),융합교육지원센터,2023-10-04,772,https://www.jj.ac.kr/jj/community/notice01.do?...,1. 공모전 개요가. 공모 명: 자기설계연계전공 교육과정 공모전 등나. 사업기간: ...,NaN,...,0.0,제목2.6666666666666665/본문1.2199312714776633/이미지1...,0.0,,0.0,,0.0,,0.0,
496,496,6999,6999+교수학습개발센터_학생주도)실전에서 사용하는 발표 꿀팁,[교수학습개발센터] JJ 학습법 특강 - (학생주도)실전에서 사용하는 발표 꿀팁,교수학습개발센터,2023-10-04,387,https://www.jj.ac.kr/jj/community/notice01.do?...,"2023-1학기 학습법노하우 경진대회 수상자, 한식조리학과 김근아 학생에게서 듣는 ...",NaN,...,0.0,제목4.0/본문0.8496732026143791/이미지0.54421768707483...,0.0,,0.0,,0.0,,0.0,
497,497,6998,6998+통합 관리자_개인정보 분쟁조정제도 강화 안내,개인정보 분쟁조정제도 강화 안내,통합 관리자,2023-10-04,417,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.0,,0.0,,0.0,,0.0,,1.0,
498,498,6997,6997+교무지원실_단체교섭 요구 노동조합 확정공고,단체교섭 요구 노동조합 확정공고,교무지원실,2023-09-28,522,https://www.jj.ac.kr/jj/community/notice01.do?...,단체교섭 요구 노동조합 확정공고「교원의 노동조합 설립 및 운영 등에 관한 법률」제6...,NaN,...,0.0,,0.0,,0.0,,0.0,,1.0,
499,499,6996,"6996+장애학생지원센터_형 인턴(일반, 장애인) 채용 안내","2023년 하반기 KOTRA 체험형 인턴(일반, 장애인) 채용 안내",장애학생지원센터,2023-09-27,535,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.0,제목0.0/본문0.0/이미지0.06633499170812604/부서0,0.0,,0.0,,0.0,,0.0,

## 알고리즘 테스트 케이스

## 알고리즘 단위 테스트
제목, 본문, 부서를 직접 입력해 카테고리 점수 계산 결과를 확인하는 테스트 함수입니다. 실제 CSV 전체를 돌리기 전에 특정 문장이 어떤 카테고리로 분류되는지 빠르게 검증할 수 있습니다.

In [ ]:
# 🔹 카테고리 점수 환산 함수 (가중치 포함)
def calculate_category_scores(title, content="", dept=""):
    # NaN 처리
    title = str(title) if pd.notna(title) else ""
    content = str(content) if pd.notna(content) else ""
    dept = str(dept) if pd.notna(dept) else ""

    # 카테고리별 점수 초기화
    category_scores = {category: 0 for category in 일반_공지.keys()}
    total_score = 0

    # 🔸 공지 제목 점수
    for category, keywords in 일반_공지.items():
        title_count = sum(title.count(keyword) for keyword in keywords)
        category_scores[category] += title_count * TITLE_WEIGHT
        total_score += title_count * TITLE_WEIGHT

    # 🔸 본문 내용 점수
    for category, keywords in 일반_공지.items():
        content_count = sum(content.count(keyword) for keyword in keywords)
        category_scores[category] += content_count * CONTENT_WEIGHT
        total_score += content_count * CONTENT_WEIGHT

    # 🔸 평균 점수 환산
    if total_score > 0:
        for category in category_scores:
            if category_scores[category] > 0:
                category_scores[category] = round(category_scores[category] / total_score, 4)

    return category_scores
# 🔹 테스트 함수
def test_category_classification(text):
    scores = calculate_category_scores(text)
    print("\n📌 테스트 입력:", text)
    for category, score in scores.items():
        print(f"{category}: {score}")

# 🔹 테스트 실행
test_category_classification("창업 경진대회 캡프")
test_category_classification("성적우수 장학금 신청 안내")
test_category_classification("신입생을 위한 진로설계 프로그램")
test_category_classification("졸업생을 위한 취업 박람회 개최")

📌 테스트 입력: 창업 경진대회 캡프
학사/수업: 0
진로/취업: 0
장학금/지원금: 0
대외활동/서포터즈: 0
공모전/경진대회: 0.4
교내행사/이벤트: 0.4
비교과/교육: 0
군 관련: 0
창업 관련: 0.2
행정: 0
기타: 0

📌 테스트 입력: 성적우수 장학금 신청 안내
학사/수업: 0.25
진로/취업: 0
장학금/지원금: 0.5
대외활동/서포터즈: 0
공모전/경진대회: 0
교내행사/이벤트: 0
비교과/교육: 0.25
군 관련: 0
창업 관련: 0
행정: 0
기타: 0

📌 테스트 입력: 신입생을 위한 진로설계 프로그램
학사/수업: 0
진로/취업: 0.5
장학금/지원금: 0
대외활동/서포터즈: 0
공모전/경진대회: 0
교내행사/이벤트: 0
비교과/교육: 0.5
군 관련: 0
창업 관련: 0
행정: 0
기타: 0

📌 테스트 입력: 졸업생을 위한 취업 박람회 개최
학사/수업: 0.5
진로/취업: 0.25
장학금/지원금: 0
대외활동/서포터즈: 0
공모전/경진대회: 0
교내행사/이벤트: 0.25
비교과/교육: 0
군 관련: 0
창업 관련: 0
행정: 0
기타: 0

## 참고: 이전 실험/보관 코드

## 이전 실험/보관 코드
아래 셀은 현재 대표 파이프라인과 별도로 남겨 둔 실험/보관 코드입니다. 형태소 분석 기반 키워드 후보 추출이나 이전 가중치 계산 방식을 비교할 때 참고하며, 메인 결과를 재현할 때는 위쪽 점수화 로직을 우선 확인하면 됩니다.

In [ ]:
# Colab, Jupyter, 로컬 모두에서 konlpy 설치
!pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading jpype1-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.11/dist-packages (from konlpy) (5.4.0)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.11/dist-packages (from konlpy) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from JPype1>=0.7.0->konlpy) (24.2)
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 93.1 MB/s eta 0:00:00
Downloading jpype1-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (494 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 494.1/494.1 kB 31.4 MB/s eta 0:00:00
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.5.2 konlpy-0.6.0

### 형태소 분석 기반 키워드 후보 추출
`konlpy`의 Okt 형태소 분석기를 사용해 공지 제목에서 자주 등장하는 명사를 추출합니다. 이 결과는 카테고리 키워드 사전을 만들거나 보완할 때 참고할 수 있습니다.

In [ ]:
import pandas as pd
from konlpy.tag import Okt
from collections import Counter

# 파일 경로
file_path = "일반공지.csv"

# 데이터 로드
df = pd.read_csv(file_path)

# 형태소 분석기 초기화
okt = Okt()

# 형태소 빈도수 계산
all_morphemes = []

# "공지 제목" 열의 형태소 추출
for title in df["공지 제목"].fillna(""):
    # 형태소 분리
    morphemes = okt.nouns(title)
    # 특수문자, 숫자 제거 (1글자 이하도 제외)
    morphemes = [token for token in morphemes if len(token) > 1 and not token.isdigit()]
    all_morphemes.extend(morphemes)

# 형태소 빈도수 계산
morpheme_freq = Counter(all_morphemes)

# 데이터프레임으로 변환
freq_df = pd.DataFrame(morpheme_freq.items(), columns=["형태소", "빈도수"])
freq_df = freq_df.sort_values(by="빈도수", ascending=False).reset_index(drop=True)

# 결과 저장
freq_df.to_csv("일반_제목_형태소.csv", index=False, encoding='utf-8-sig')
print("✅ 형태소 빈도수 데이터프레임이 title_morpheme_frequency.csv로 저장되었습니다.")

# 결과 미리보기
print(freq_df.head(20))

✅ 형태소 빈도수 데이터프레임이 title_morpheme_frequency.csv로 저장되었습니다.
     형태소  빈도수
0     안내  317
1     모집  211
2     센터  158
3     학년  107
4     학습  107
5     학기  100
6     교육   71
7     개발   63
8     교수   61
9     학생   60
10    대학   54
11    지원   53
12    창업   53
13  프로그램   51
14    공유   39
15    사업   37
16    전북   35
17    특강   30
18    인권   28
19    지역   28

### 이전 버전 분류 로직 보관
마감일 추출 결과 파일을 입력으로 사용한 과거 분류 코드입니다. 현재 메인 로직과 비교하면서 가중치나 저장 형식이 어떻게 바뀌었는지 확인하는 백업 자료입니다.

In [ ]:
import pandas as pd

# 🔹 파일 로드
file_path = "마감일_추출결과_v1.csv"
df = pd.read_csv(file_path)
noti_case = '일반'

# 🔹 카테고리 그룹 딕셔너리
if noti_case == '일반':
    category_keywords = 일반_공지
    department_keywords = 부서_분류
elif noti_case == '장학':
    category_keywords = 장학_공지
    department_keywords = 부서_분류
elif noti_case == '채용':
    category_keywords = 채용_공지
    department_keywords = 부서_분류
elif noti_case == '학사':
    category_keywords = 학사_공지
    department_keywords = 부서_분류

# 🔹 가중치 설정
TITLE_WEIGHT = 3     # 공지 제목
CONTENT_WEIGHT = 2   # 본문 내용
DEPT_WEIGHT = 0      # 부서 이름
IMAGE_WEIGHT = 2     # 이미지 텍스트

# 🔹 카테고리 점수 환산 함수 (문자열 길이 기반)
def calculate_category_scores(title, content, dept, image_text):
    # NaN 처리
    title = str(title) if pd.notna(title) else ""
    content = str(content) if pd.notna(content) else ""
    dept = str(dept) if pd.notna(dept) else ""
    image_text = str(image_text) if pd.notna(image_text) else ""

    # 카테고리별 점수 초기화
    category_scores = {category: 0 for category in category_keywords.keys()}
    total_score = 0

    # 🔸 공지 제목 점수
    for category, keywords in category_keywords.items():
        title_count = sum(title.count(keyword) for keyword in keywords)
        category_scores[category] += ( title_count * TITLE_WEIGHT*10 ) / (len(title) + 1)
        total_score += (title_count * TITLE_WEIGHT*10) / (len(title) + 1)

    # 🔸 본문 내용 점수
    for category, keywords in category_keywords.items():
        content_count = sum(content.count(keyword) for keyword in keywords)
        category_scores[category] += ( content_count * CONTENT_WEIGHT*10 ) / (len(content) + 1)
        total_score += (content_count * CONTENT_WEIGHT*10) / (len(content) + 1)

    # 🔸 부서 이름 점수
    for category, keywords in department_keywords.items():
        dept_count = sum(dept.count(keyword) for keyword in keywords)
        if category in category_scores:
            category_scores[category] += ( dept_count * DEPT_WEIGHT*10 ) / (len(dept) + 1)
            total_score += (dept_count * DEPT_WEIGHT*10) / (len(dept) + 1)

    # 🔸 이미지 텍스트 점수
    for category, keywords in category_keywords.items():
        image_count = sum(image_text.count(keyword) for keyword in keywords)
        category_scores[category] += ( image_count * IMAGE_WEIGHT*10 ) / (len(image_text) + 1)
        total_score += (image_count * IMAGE_WEIGHT*10) / (len(image_text) + 1)

    # 🔸 평균 점수 환산
    if total_score > 0:
        for category in category_scores:
            if category_scores[category] > 0:
                category_scores[category] = round(category_scores[category] / total_score, 4)
    else:
        # 🔹 모든 점수가 0일 경우 "기타" 카테고리 추가
        category_scores["기타"] = 1.0

    return category_scores

# 🔹 데이터프레임에 카테고리 점수 추가
category_columns = list(category_keywords.keys()) + ["기타"]
for col in category_columns:
    if col not in df.columns:
        df[col] = 0.0

# 🔹 각 공지사항에 대해 점수 계산
for idx, row in df.iterrows():
    title = row.get("공지 제목", "")
    content = row.get("본문 내용", "")
    dept = row.get("부서", "")
    image_text = row.get("이미지 텍스트", "")

    scores = calculate_category_scores(title, content, dept, image_text)
    for category, score in scores.items():
        df.at[idx, category] = score

# 🔹 결과 저장
output_file = f"②_{noti_case}+마감일v1_카테고리_점수환산({TITLE_WEIGHT}-{CONTENT_WEIGHT}-{DEPT_WEIGHT}-{IMAGE_WEIGHT}).csv"
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: {output_file}")

# 🔹 최종 데이터프레임 출력
df

✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: ②_일반+마감일v1_카테고리_점수환산(3-2-0-2).csv

,Unnamed: 0,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,...,진로/취업,장학금/지원금,대외활동/서포터즈,공모전/경진대회,교내행사/이벤트,비교과/교육,군 관련,창업 관련,행정,기타
0,0,공지,공지+관리자_ 백마응원단에서 신입단원을 모집합니다,전주대학교 백마응원단에서 신입단원을 모집합니다,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,"안녕하세요, 전주대학교 학생 여러분전주대학교의 새로운 응원 문화를 선도할 백마응원...",NaN,...,0.0000,0.0981,0.7447,0.0000,0.0590,0.0491,0.0,0.0,0.0000,0.0
1,1,공지,공지+관리자_제13회 미래전북포럼 개최 안내,제13회 미래전북포럼 개최 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.8985,0.0677,0.0,0.0,0.0113,0.0
2,2,공지,공지+관리자_장(학생)예비군 전입신고서 제출 안내,2025학년도 1학기 직장(학생)예비군 전입신고서 제출 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,* 자세한 내용은 첨부문서 참조,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.5,0.0,0.0000,0.0
3,3,7492,7492+RIS사업단_차 수준별 기초학력증진 프로그램 안내,2025학년도 JST 공유대학 제1차 수준별 기초학력증진 프로그램 안내,RIS사업단,2025-04-02,138,https://www.jj.ac.kr/jj/community/notice01.do?...,신청기간: 2025. 4. 1.(화) ~ 2025. 4. 10.(목)신청방법: JS...,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.6774,0.0,0.0,0.0000,0.0
4,4,7491,7491+대학일자리플러스센터_Dream-JOB 스터디 참여자 모집,[대학일자리플러스센터] 2025학년도 Dream-JOB 스터디 참여자 모집,대학일자리플러스센터,2025-04-01,155,https://www.jj.ac.kr/jj/community/notice01.do?...,취업을 준비 중이신가요?같은 기업 혹은 직무를 목표로 하는 팀들과 함께하는실전 취업...,NaN,...,0.5594,0.0000,0.0216,0.0000,0.0216,0.2828,0.0,0.0,0.0000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,7000,7000+융합교육지원센터_총 장학금 400만원/~11월 5일),2023학년도 자기설계전공 교육과정 공모전(총 장학금 400만원/~11월 5일),융합교육지원센터,2023-10-04,772,https://www.jj.ac.kr/jj/community/notice01.do?...,1. 공모전 개요가. 공모 명: 자기설계연계전공 교육과정 공모전 등나. 사업기간: ...,NaN,...,0.0033,0.1325,0.0000,0.0692,0.0692,0.4004,0.0,0.0,0.0000,0.0
496,496,6999,6999+교수학습개발센터_학생주도)실전에서 사용하는 발표 꿀팁,[교수학습개발센터] JJ 학습법 특강 - (학생주도)실전에서 사용하는 발표 꿀팁,교수학습개발센터,2023-10-04,387,https://www.jj.ac.kr/jj/community/notice01.do?...,"2023-1학기 학습법노하우 경진대회 수상자, 한식조리학과 김근아 학생에게서 듣는 ...",NaN,...,0.0000,0.0000,0.0000,0.0213,0.0542,0.8808,0.0,0.0,0.0000,0.0
497,497,6998,6998+통합 관리자_개인정보 분쟁조정제도 강화 안내,개인정보 분쟁조정제도 강화 안내,통합 관리자,2023-10-04,417,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0,0.0000,1.0
498,498,6997,6997+교무지원실_단체교섭 요구 노동조합 확정공고,단체교섭 요구 노동조합 확정공고,교무지원실,2023-09-28,522,https://www.jj.ac.kr/jj/community/notice01.do?...,단체교섭 요구 노동조합 확정공고「교원의 노동조합 설립 및 운영 등에 관한 법률」제6...,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0,0.0000,1.0
499,499,6996,"6996+장애학생지원센터_형 인턴(일반, 장애인) 채용 안내","2023년 하반기 KOTRA 체험형 인턴(일반, 장애인) 채용 안내",장애학생지원센터,2023-09-27,535,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,...,0.9223,0.0000,0.0086,0.0000,0.0173,0.0346,0.0,0.0,0.0000,0.0

### 이전 버전 일반공지 분류 저장
일반공지 OCR 포함 파일을 대상으로 카테고리 점수를 계산하고 저장하는 이전 방식입니다. 현재 구조와 중복될 수 있으므로, 재사용 시 입력 파일과 가중치 설정을 먼저 확인해야 합니다.

In [ ]:
import pandas as pd

# 🔹 파일 로드
file_path = "일반공지+이미지텍스트_포함.csv"
df = pd.read_csv(file_path)
noti_case = '일반'

# 🔹 카테고리 그룹 딕셔너리
if noti_case == '일반':
    category_keywords = 일반_공지
    department_keywords = 부서_분류
elif noti_case == '장학':
    category_keywords = 장학_공지
    department_keywords = 부서_분류
elif noti_case == '채용':
    category_keywords = 채용_공지
    department_keywords = 부서_분류
elif noti_case == '학사':
    category_keywords = 학사_공지
    department_keywords = 부서_분류

# 🔹 가중치 설정
TITLE_WEIGHT = 3     # 공지 제목
CONTENT_WEIGHT = 2   # 본문 내용
DEPT_WEIGHT = 0      # 부서 이름
IMAGE_WEIGHT = 2     # 이미지 텍스트

# 🔹 카테고리 점수 환산 함수 (가중치 포함)
def calculate_category_scores(title, content, dept, image_text):
    # NaN 처리
    title = str(title) if pd.notna(title) else ""
    content = str(content) if pd.notna(content) else ""
    dept = str(dept) if pd.notna(dept) else ""
    image_text = str(image_text) if pd.notna(image_text) else ""

    # 카테고리별 점수 초기화
    category_scores = {category: 0 for category in category_keywords.keys()}
    total_score = 0

    # 🔸 공지 제목 점수
    for category, keywords in category_keywords.items():
        title_count = sum(title.count(keyword) for keyword in keywords)
        category_scores[category] += title_count * TITLE_WEIGHT
        total_score += title_count * TITLE_WEIGHT

    # 🔸 본문 내용 점수
    for category, keywords in category_keywords.items():
        content_count = sum(content.count(keyword) for keyword in keywords)
        category_scores[category] += content_count * CONTENT_WEIGHT
        total_score += content_count * CONTENT_WEIGHT

    # 🔸 부서 이름 점수
    for category, keywords in department_keywords.items():
        dept_count = sum(dept.count(keyword) for keyword in keywords)
        if category in category_scores:
            category_scores[category] += dept_count * DEPT_WEIGHT
            total_score += dept_count * DEPT_WEIGHT

    # 🔸 이미지 텍스트 점수
    for category, keywords in category_keywords.items():
        image_count = sum(image_text.count(keyword) for keyword in keywords)
        category_scores[category] += image_count * IMAGE_WEIGHT
        total_score += image_count * IMAGE_WEIGHT

    # 🔸 평균 점수 환산
    if total_score > 0:
        for category in category_scores:
            if category_scores[category] > 0:
                category_scores[category] = round(category_scores[category] / total_score, 4)
    else:
        # 🔹 모든 점수가 0일 경우 "기타" 카테고리 추가
        category_scores["기타"] = 1.0

    return category_scores

# 🔹 데이터프레임에 카테고리 점수 추가
category_columns = list(category_keywords.keys()) + ["기타"]
for col in category_columns:
    if col not in df.columns:
        df[col] = 0.0

# 🔹 각 공지사항에 대해 점수 계산
for idx, row in df.iterrows():
    title = row.get("공지 제목", "")
    content = row.get("본문 내용", "")
    dept = row.get("부서", "")
    image_text = row.get("이미지 텍스트", "")

    scores = calculate_category_scores(title, content, dept, image_text)
    for category, score in scores.items():
        df.at[idx, category] = score

# 🔹 결과 저장
output_file = f"{noti_case}_카테고리_점수환산({TITLE_WEIGHT}-{CONTENT_WEIGHT}-{DEPT_WEIGHT}-{IMAGE_WEIGHT}).csv"
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: {output_file}")

# 🔹 최종 데이터프레임 출력
df

✅ 카테고리 점수가 포함된 데이터프레임이 저장되었습니다: 일반_카테고리_점수환산(3-2-0-2).csv

,등록 번호,기본 제목,공지 제목,부서,등록일,조회수,링크,본문 내용,카테고리,이미지 링크,...,진로/취업,장학금/지원금,대외활동/서포터즈,공모전/경진대회,교내행사/이벤트,비교과/교육,군 관련,창업 관련,행정,기타
0,공지,공지+관리자_ 백마응원단에서 신입단원을 모집합니다,전주대학교 백마응원단에서 신입단원을 모집합니다,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,"안녕하세요, 전주대학교 학생 여러분전주대학교의 새로운 응원 문화를 선도할 백마응원...",NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,...,0.0000,0.1600,0.5200,0.0000,0.1600,0.0800,0.0000,0.0,0.0000,0.0
1,공지,공지+관리자_제13회 미래전북포럼 개최 안내,제13회 미래전북포럼 개최 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,...,0.0000,0.0000,0.0000,0.0000,0.3333,0.4444,0.0000,0.0,0.0741,0.0
2,공지,공지+관리자_장(학생)예비군 전입신고서 제출 안내,2025학년도 1학기 직장(학생)예비군 전입신고서 제출 안내,관리자,2025-04-03,0,https://www.jj.ac.kr/jj/community/notice01.do?...,* 자세한 내용은 첨부문서 참조,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.6667,0.0,0.0000,0.0
3,7492,7492+RIS사업단_차 수준별 기초학력증진 프로그램 안내,2025학년도 JST 공유대학 제1차 수준별 기초학력증진 프로그램 안내,RIS사업단,2025-04-02,138,https://www.jj.ac.kr/jj/community/notice01.do?...,신청기간: 2025. 4. 1.(화) ~ 2025. 4. 10.(목)신청방법: JS...,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.5000,0.0000,0.0,0.0000,0.0
4,7491,7491+대학일자리플러스센터_Dream-JOB 스터디 참여자 모집,[대학일자리플러스센터] 2025학년도 Dream-JOB 스터디 참여자 모집,대학일자리플러스센터,2025-04-01,155,https://www.jj.ac.kr/jj/community/notice01.do?...,취업을 준비 중이신가요?같은 기업 혹은 직무를 목표로 하는 팀들과 함께하는실전 취업...,NaN,https://www.jj.ac.kr/_attach/jj/editor-image/2...,...,0.4742,0.0000,0.0412,0.0000,0.0412,0.2371,0.0000,0.0,0.0000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,7000,7000+융합교육지원센터_총 장학금 400만원/~11월 5일),2023학년도 자기설계전공 교육과정 공모전(총 장학금 400만원/~11월 5일),융합교육지원센터,2023-10-04,772,https://www.jj.ac.kr/jj/community/notice01.do?...,1. 공모전 개요가. 공모 명: 자기설계연계전공 교육과정 공모전 등나. 사업기간: ...,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,...,0.0072,0.0682,0.0000,0.0449,0.0449,0.4452,0.0000,0.0,0.0000,0.0
496,6999,6999+교수학습개발센터_학생주도)실전에서 사용하는 발표 꿀팁,[교수학습개발센터] JJ 학습법 특강 - (학생주도)실전에서 사용하는 발표 꿀팁,교수학습개발센터,2023-10-04,387,https://www.jj.ac.kr/jj/community/notice01.do?...,"2023-1학기 학습법노하우 경진대회 수상자, 한식조리학과 김근아 학생에게서 듣는 ...",NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,...,0.0000,0.0000,0.0000,0.0571,0.1143,0.7429,0.0000,0.0,0.0000,0.0
497,6998,6998+통합 관리자_개인정보 분쟁조정제도 강화 안내,개인정보 분쟁조정제도 강화 안내,통합 관리자,2023-10-04,417,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,1.0
498,6997,6997+교무지원실_단체교섭 요구 노동조합 확정공고,단체교섭 요구 노동조합 확정공고,교무지원실,2023-09-28,522,https://www.jj.ac.kr/jj/community/notice01.do?...,단체교섭 요구 노동조합 확정공고「교원의 노동조합 설립 및 운영 등에 관한 법률」제6...,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,1.0
499,6996,"6996+장애학생지원센터_형 인턴(일반, 장애인) 채용 안내","2023년 하반기 KOTRA 체험형 인턴(일반, 장애인) 채용 안내",장애학생지원센터,2023-09-27,535,https://www.jj.ac.kr/jj/community/notice01.do?...,NaN,NaN,https://www.jj.ac.kr/_attach/jj/old-editor-ima...,...,0.6538,0.0000,0.0385,0.0000,0.0769,0.1538,0.0000,0.0,0.0000,0.0